output   = "models"
wipe     = true
no-tests = true

 [mysql]
   dbname  = "robotenok"
   host    = "localhost"
   port    = 3306
   user    = "admin"
   pass    = "Zero_twO*Rengyou"
   sslmode = "false"