// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Classes          string
	ConfirmedDevices string
	Costs            string
	CostsReceipts    string
	CourseGroups     string
	Courses          string
	GroupCurators    string
	GroupStudents    string
	GroupTypes       string
	Groups           string
	Images           string
	PaymentObjects   string
	Payments         string
	Students         string
	Users            string
	Visits           string
}{
	Classes:          "classes",
	ConfirmedDevices: "confirmed_devices",
	Costs:            "costs",
	CostsReceipts:    "costs_receipts",
	CourseGroups:     "course_groups",
	Courses:          "courses",
	GroupCurators:    "group_curators",
	GroupStudents:    "group_students",
	GroupTypes:       "group_types",
	Groups:           "groups",
	Images:           "images",
	PaymentObjects:   "payment_objects",
	Payments:         "payments",
	Students:         "students",
	Users:            "users",
	Visits:           "visits",
}
